export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const GET_TOP_QUESTIONS = 'GET_TOP_QUESTIONS';
export const GET_TAG_QUESTIONS = 'GET_TAG_QUESTIONS';
export const QUESTION_ERROR = 'QUESTION_ERROR';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';