export const GET_ANSWERS = 'GET_ANSWERS';
export const ANSWER_ERROR = 'ANSWER_ERROR';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const ADD_ANSWER = 'ADD_ANSWER';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const ANSWERS_LOADING = 'ANSWERS_LOADING';
export const UPDATE_BLOCKED_ANSWER = 'UPDATE_BLOCKED_ANSWER';