export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_MODERATORS = 'GET_MODERATORS';
export const GET_ADMINISTRATORS = 'GET_ADMINISTRATORS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_ERROR = 'USERS_ERROR';
export const GET_USER = 'GET_USER';
export const GET_SEARCH_USERS = 'GET_SEARCH_USERS';